pipeline {
    agent any

    parameters {
        string(defaultValue: "default", description:"Input the name of this deployment",name:"deployment")
        choice(choices: ["EU-WEST-2A","EU-WEST-2B","EU-WEST-2C"], description: "Which AZ would you like to use?", name: "az")
        booleanParam(defaultValue:false, description:"Deploy to prod?", name:"confirm")
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        
        stage("Complete"){
            steps{
                sh "echo The object was deployed to ${params.az} using the deployment: ${params.deployment}"
            }
        }
    }
}
